name: Download pvt pkg

on:
  workflow_dispatch:

jobs:  
  read:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: Run a multi-line script
        run: |
          nwo="srahul3/oci-image-sdk-private"
          tag="2.0.1"
          host="https://ghcr.io"
          manifest_uri="${host}/v2/${nwo}/manifests/${tag}"
          GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          curl -X GET "${manifest_uri}" -H "Authorization: Bearer ${GHCR_TOKEN}" -H "Accept: application/vnd.oci.image.manifest.v1+json"
          
      - name: Run download blob
        run: |
          nwo="srahul3/oci-image-sdk-private"          
          host="https://ghcr.io"
          manifest_uri="${host}/v2/${nwo}/blobs/sha256:30c26b5dfc924473b2468833d673acc3f4c11c1fc6f930ccb1ed03fdb6050942"
          GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          curl -I -X GET "${manifest_uri}" -H "Authorization: Bearer ${GHCR_TOKEN}"

          
